spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 174901881980-h19g4ghkjju4juhm6qf0tqgclsnki5ip.apps.googleusercontent.com
            client-secret: gBBEYsLymVo8OKZuPLZISJPO